[KOJI-123] Data Grid
shogun-hearth/hajimari pull request #69
Opened 2022-11-12 01:14 UTC by eynglv

2022-11-15 17:22 UTC, brianclee-gh approved these changes

2022-11-17 19:17 UTC, smurmus requested changes

2022-11-17 19:17 UTC, smurmus commented on src/components/DataGrid/DataGrid.tsx
> +  height: string;
the former two are more straightforward but could you add comments above these two props for what they do? (`pageSize` and `height`)

2022-11-17 19:17 UTC, smurmus commented on src/components/DataGrid/DataGrid.tsx
> +  height: string;
and also using the `@default` syntax we use in a few places for the `pageSize` prop

2022-11-17 19:17 UTC, smurmus commented on src/components/DataGrid/DataGrid.tsx
> +const useStyles = makeStyles({
should be able to use `styled` here; don't want to use `makeStyles` anymore!

the css classes should be able to be used the same way

2022-11-18 21:54 UTC, smurmus approved these changes
small comment around props naming!

2022-11-18 21:54 UTC, smurmus commented on src/components/DataGrid/DataGrid.tsx
> +export interface Props extends DataGridProps {
should do `export interface DataGridProps extends MuiDataGridProps` (import native props with the Mui prefix)

2022-11-18 22:55 UTC, merged